---
title: "Reports"
site: distill::distill_website
listing: 
  posts:
    - nzavs
    - nzavsnetwork
    - religious_simpsons_paradox
    - covid
    - mus
    - police
    - spiriteuthanasia
    - k6-income

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
options(width = 60)
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x, options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"', options$max.height)
    )
    hook_output(x, options)
  })
})
```

```{r, include = FALSE}
library(here)
# GitHub pages
file.create("docs/.nojekyll", showWarnings = FALSE)
# Ensure directories exist
dir.create("data", FALSE)
```

<!-- ```{r render-everything, include = FALSE, eval = FALSE} -->
<!-- # Use to render all posts (article and slide deck) if needed -->
<!-- library(rmarkdown) -->
<!-- posts <- list.files( -->
<!--   "_posts", recursive = TRUE, pattern = ".Rmd", full.names = TRUE -->
<!--   ) -->
<!-- purrr::walk(posts, render) -->
<!-- ``` -->
