---
title: "COVID-19 Lockdown"
description: |
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
date: 2021-FEB-28
output:
  distill::distill_article:
    self_contained: false
    toc: true
bibliography: bib.bib
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "figs/",
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  echo = FALSE,
  fig.width = 10,
  fig.height = 8
)
#results="hide",
#fig.width= 8,
#fig.height=,
#fig.fullwidth = TRUE)
```


```{r load_libraries, include=FALSE}
library("tidyverse")
library("easystats")
library("lme4")
library("splines")
library("mgcv")
library("table1")
library("ggplot2")
library("ggeffects")
library("gghighlight")
#library("Amelia")
library("magrittr")
library("patchwork")
library("sjPlot")
library("texreg")
library("tinytex")
library("kableExtra")
library("ggpubr")
#library("viridis")
#library("wesanderson")
library("ggsci")
library("report")
library("papaja")
library("here")
library("citr")
library("here")
library("brms")
library("rstan")
library("rstanarm")
# library("tidybayes")
library("lubridate")
library("ggdag")
library("viridisLite")
#library("glmmTMB")
library("bmlm")
library("bayesplot")
library("broom")
library("purrr")
# rstan options
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores ())
theme_set(theme_classic())
```


```{r}
# import data
df <- readRDS(here::here("data", "df"))
```

```{r}

# timeline
ord_dates_class <- c(
  "BaseLine_2018_19_w10", 
  "Pre_COVID_2019_w11", 
  "Jan_Feb_2020", 
  "Early_March_2020", 
  "L4_Lockdown_2020",
  "Post_Lockdown_2020")
rm(cv)

cv <- df %>%
  dplyr::filter(YearMeasured == 1) %>%
  dplyr::filter(Wave == 2018 | Wave == 2019) %>%
  dplyr::group_by(Id) %>% filter(n() > 1) %>%
  dplyr::filter(n() != 0) %>%
  dplyr::ungroup(Id) %>%
  dplyr::mutate(Covid_Timeline =
                 # ifelse(
                 # TSCORE %in% 3837:3894,
                 # "Baseling",
                    as.factor(ifelse(
                      TSCORE %in% 3895:3921,
                      "Early_March_2020",
                      ifelse(
                        TSCORE %in% 3921:3954,
                        "L4_Lockdown_2020",
                        ifelse(
                          TSCORE > 3954,
                          "Post_Lockdown_2020",
                          ifelse(
                            TSCORE %in% 3842:3894,
                            "Jan_Feb_2020",
                          ifelse(
                            TSCORE %in% 3665:3842 &
                              Wave == 2019,
                            "Pre_COVID_2019_w11",
                            "BaseLine_2018_19_w10"
                          )
                        )
                      )
                    ) 
                 ) ))%>%
  dplyr::mutate(PrePostCovid =
                  ifelse(
                    TSCORE > 3895, "post_covid",
                    ifelse(
                      TSCORE < 3895 &
                        Wave == 2019,
                      "before_COVID_wave11",
                      "baseline_wave10"
                    )
                  ))%>% 
  dplyr::select(
    TSCORE,
    Wave,
    Partner,
    PrePostCovid,
    Rel.Conflict,
    Rel.Satisfaction,
    Hours.SocialMedia,
    Hours.Exercise,
    Hours.Internet,
    Hours.News,
    Hours.Family,
    Hours.Friends,
    Hours.Housework,
    Hours.Children,
    Hours.Religious,
    Hours.Work,
    Hours.Community,
    Family.Time,
    Community.Time,
    Friends.Time,
    Family.Money,
    Friends.Money,
    Community.Money,
    years,
    Id,
    Parent,
    SWB.SatPWI02, # your health
    Hours.Work,
    Hours.Exercise,
    LIFEMEANING,
    KESSLER6,
    SWB.SatPWI03, # your future security
    #  K6sum,
    KESSLER6sum,
    Age,
    Male,
    Relid,
    Pol.Orient,
    Urban,
    GenCohort,
    Edu,
    YearMeasured,
    Covid_Timeline,
    HLTH.SleepHours,
    HLTH.Fatigue,
    LIFESAT,
    PWI,
    EthnicCats,
    NZdep,
    Partner,
    Pol.Orient,
    Urban,
    Euro,
    Religious,
    NZdep,
    WSCORE,
    Religion.Church,
    Emp.JobSecure,
    Emp.JobSat,
    Emp.JobValued,
    Alcohol.Intensity,
    Alcohol.Frequency
  ) %>%
  dplyr::group_by(Id) %>% filter(n() > 1) %>%
  dplyr::filter(n() != 0) %>%
  dplyr::ungroup(Id) %>%
  dplyr::filter(!is.na(KESSLER6sum),
                !is.na(LIFEMEANING)) %>%
  dplyr::mutate(
    Urban = (Urban),
    Euro = (Euro),
    Religious = as.factor(Religious),
    Your_Health = (SWB.SatPWI02),
    Your_Future_Security = SWB.SatPWI03,
    Covid_Timeline = as.factor(Covid_Timeline)
  ) %>%
  dplyr::mutate(
    WSCORE = as.factor(WSCORE),
    EduC = scale(as.numeric(Edu), scale = F, center = TRUE),
    AgeDecadeC = scale(Age, scale = F, center = T) / 10,
    Hours.Work10 = as.integer(Hours.Work) / 10,
    Hours.Sleep = as.integer(HLTH.SleepHours),
    Hours.Exercise = as.integer(Hours.Exercise),
    Fatigue = as.integer(HLTH.Fatigue),
    K6sum = as.integer(KESSLER6 * 6),
    LIFEMEANING_S = scale(LIFEMEANING),
    NZdepS = scale(NZdep),
    PolOrientS = scale(Pol.Orient, scale = T, center = T),
    Relid_S = scale(Relid, scale = T, center = T),
    Conservative = Pol.Orient,
    hours.exercise_s = scale(Hours.Exercise),
    k6_s = scale(KESSLER6sum),
    Conservative_S = PolOrientS,
    Religion_Church_S = scale(Religion.Church),
    Emp.JobSecure_S = scale(Emp.JobSecure),
    KESSLER6sum = as.integer(KESSLER6sum),
    Alcohol.Intensity_S = scale(Alcohol.Intensity),
    Alcohol.Frequency_S = scale(Alcohol.Frequency),
    Hours.Work = as.integer(Hours.Work),
    Hours.Exercise = as.integer(Hours.Exercise),
    yearS = years - min(years)
  ) %>%
  dplyr::mutate(Covid_Timeline = forcats::fct_relevel(Covid_Timeline, ord_dates_class))

cv <- cbind(cv,
            demean(
              cv,
              select = c(
                "KESSLER6sum",
                "k6_s",
                "hours.exercise_s",
                "Hours.Sleep",
                "Hours.Work10",
                "Hours.Exercise",
                "Hours.Children",
                "Hours.Internet",
                "Hours.Friends",
                "Hours.Family",
                "Hours.Religious",
                "Hours.Community",
                "Rel.Satisfaction",
                "Rel.Conflict",
                "Family.Time",
                "Family.Money",
                "Friends.Time",
                "Friends.Money",
                "Community.Time",
                "Community.Money",
                "Fatigue",
                "Alcohol.Intensity",
                "Alcohol.Frequency"
              ),
              group = "Id"
            ))

cv$Hours.Children_within
table(cv$Covid_Timeline)
```

# Draw dag 

```{r}
library("ggdag")
tidy_k6_dag3 <- dagify(
  k6  ~ covid + income + jobsecurity + age + fatigue + sleep + 
    childcare + partner + male + exercise + healthsecurity,
  income ~ hourswork + jobsecurity + edu + ethnicity + male + covid,
  exercise ~ age + ethnicity, 
  childcare ~ hourswork + male, 
  partner ~ jobsecurity + childcare + hourswork,
  fatigue ~  age + hourswork + sleep + exercise,
  sleep ~   age + hourswork + exercise + jobsecurity,
  jobsecurity ~ hourswork + buisnessconfidence + covid,
  healthsecurity ~ govconfidence + covid + edu + exercise + age,
  govconfidence ~ covid + edu, 
  buisnessconfidence ~ govconfidence + covid,
  exposure =  "covid",
  outcome =   "k6",
  labels = c(k6 = "Kessler 6", 
             covid = "Covid Timeline", 
             fatigue = "fatigue",
             income = "income",
             age = "age",
             healthsecurity = "health security",
             govconfidence = "government confidence",
             exercise = "exercise",
             sleep = "sleep",
             buisnessconfidence = "buisness confidence",
             childcare = "childcare",
             partner = "partner \n dissatifaction",
             employed = "employed",
             jobsecurity = "job security",
             exercise = "exercise",
             edu = "education",
             ethnicity = "ethnicity",
             male = "male",
             hourswork = "hours work"
             )) %>%
    control_for(c("exercise"))
# no to healthsecurity
# no to childcare
# no to partner 
# no to buisness confidence
# no to income
# big no to fatigue!
# big no no to sleep
# yes to exercise! 

ggdag_adjust(tidy_k6_dag3, text = FALSE, use_labels = "label", collider_lines = TRUE)

```

```{r }
# graph adjustment sets
ggdag::ggdag_adjustment_set(tidy_k6_dag3, node_size = 14) +
  theme(legend.position = "bottom") + theme_dag_blank()
```

##  The GGDAG package will find colliders

```{r }
#Colliders
ggdag::ggdag_collider(tidy_k6_dag3,
                      from = "covid",
                      to = "k6") +   theme_dag_blank()
```

## The adjustment set command tells you which variables to include condition 







## What if you adopt a causal salad approach? 
```{r}
ggdag_drelationship(
  tidy_k62,
  from = "covid",
  to = "k6",
  controlling_for = c("male", "age", "sleep", "income", "mean", "rel"),
  collider_lines = TRUE
) + theme_dag_blank()
```



```{r}
k6_cv <- brm(KESSLER6sum_within ~ Covid_Timeline + (1|Id), cv, file = here::here("models","k6_cv"))
summary(k6_cv)


m_exercise <- lmer(hours.exercise_s ~ Covid_Timeline + (1|Covid_Timeline/Id), cv)
summary(m_exercise)

k6 <- lmer(k6_s ~ Covid_Timeline + (1|Covid_Timeline/Id), cv)
k6sum <- glmer(KESSLER6sum ~ Covid_Timeline + (1|Covid_Timeline/Id), family ="poisson", data =cv)

cv$hours.exercise_s
sum(is.na(cv$hours.exercise_s))/nrow(cv)

ts <- lmer(Fatigue_within ~  Covid_Timeline + (1|Id), data = cv)
summary(ts)
estimate_means(ts)
estimate_contrasts(ts)
ts <- lmer(Alcohol.Frequency_within ~  Covid_Timeline + (1|Id), data = cv)
summary(ts)
estimate_means(ts)
estimate_contrasts(ts)
ts <- lmer(Alcohol.Intensity_S~  Covid_Timeline + (1|Id), data = cv)
summary(ts)
estimate_means(ts)
estimate_contrasts(ts)
she <- lmer(hours.exercise_s_within ~ Covid_Timeline + (1|Id), data = cv)

he <- glmer(Hours.Exercise ~ Covid_Timeline + (1|Id/Covid_Timeline), family ="poisson", data =cv)

he2 <- glmer(KESSLER6sum ~ Covid_Timeline +  hours.exercise_s_within +  hours.exercise_s_between +
               (1 |Covid_Timeline), family ="poisson", data =cv)

summary(he)


estimate_contrasts(k6)%>%
  slice(1:5)
estimate_means(k6)%>%
  slice(1:5)

estimate_contrasts(he2)%>%
  slice(1:5)
estimate_means(he2)%>%
  slice(1:5)

### 

estimate_contrasts(she)
estimate_means(she)

estimate_contrasts(he)%>%
  slice(1:5)
estimate_means(he)%>%
  slice(1:5)



m_fat<- lmer(Fatigue_within ~ Covid_Timeline + (1|Id), cv)
summary(m_fat)


m_friends <- lmer(Hours.Friends_within ~ Covid_Timeline + (1|Id), cv)
summary(m_friends)

m_religious <- lmer(Hours.Religious_within ~ Covid_Timeline + (1|Id), cv)
summary(m_religious)


m_family <- lmer(Hours.Family_within ~ Covid_Timeline + (1|Id), cv)
summary(m_family)

cvp <- cv %>%
  dplyr::filter(Partner ==1)

table(cvp$Covid_Timeline)


m_relsatisfaction <- lmer(Rel.Satisfaction_within ~ Covid_Timeline + (1|Id), cvp)
summary(m_relsatisfaction)


m_relsatisfaction <- lmer(Rel.Satisfaction_within ~ Covid_Timeline + (1|Id), cvp)
summary(m_relsatisfaction)


cv$Fatigue
cvna<-cv%>%
  dplyr::filter(!is.na(Fatigue))


m_relconflict <- lmer(Rel.Conflict_within ~ Covid_Timeline + (1|Id), cvp)
summary(m_relconflict)
cv$Hours.Children
cv$Hours.Children

cvparent <- cv %>% 
   dplyr::mutate(childhours = ifelse(Hours.Children > 0,1,0))%>%
   dplyr::filter(childhours==1) %>%
   dplyr::filter(Parent==1)
                
table(cvparent$Covid_Timeline)

m_child<- lmer(Hours.Children_within ~ Covid_Timeline + (1|Id), cvparent)
summary(m_child)

```

```{r}
means <- estimate_means(k6_cv)
ggplot(cv, aes(x = Covid_Timeline, y = KESSLER6sum_within, fill = Covid_Timeline)) +
  geom_violin() +
  geom_jitter2(width = 0.05, alpha = 0.5) +
  geom_line(data = means, aes(y = Mean, group = 1), size = 1) +
  geom_pointrange(data = means, 
                  aes(y = Mean, ymin = CI_low, ymax = CI_high),
                  size = 1, 
                  color = "white") +
  theme_modern()






means <- estimate_means(m_fat)
ggplot(cv, aes(x = Covid_Timeline, y = Fatigue_within, fill = Covid_Timeline)) +
  geom_violin() +
  geom_jitter2(width = 0.05, alpha = 0.5) +
  geom_line(data = means, aes(y = Mean, group = 1), size = 1) +
  geom_pointrange(data = means, 
                  aes(y = Mean, ymin = CI_low, ymax = CI_high),
                  size = 1, 
                  color = "white") +
  theme_modern()


means <- estimate_means(m_relconflict)
ggplot(cvp, aes(x = Covid_Timeline, y = Rel.Conflict_within, fill = Covid_Timeline)) +
  geom_violin() +
  geom_jitter2(width = 0.05, alpha = 0.5) +
  geom_line(data = means, aes(y = Mean, group = 1), size = 1) +
  geom_pointrange(data = means, 
                  aes(y = Mean, ymin = CI_low, ymax = CI_high),
                  size = 1, 
                  color = "white") +
  theme_modern()

```


```{r}
estimate_contrasts(m_fat)%>%
  slice(1:6)
estimate_means(m_fat)%>%
  slice(1:6)
```






```{r cache = TRUE}
estimate_contrasts(m0)
library(see)
library(ggplot2)
plot(estimate_contrasts(k6_cv)%>%
  slice(1:6), estimate_means(k6_cv)%>%
  slice(1:6)) +
  theme_modern()
```


```{r}
bmlm::mlm_path_plot(
  xlab = "Covid\nCondition", 
  ylab = "Kessler6\n Distress", 
  mlab = "Fatigue"
  )
```

```{r}
library(tidyverse)
library(patchwork)
p1 <- cv %>% 
  ggplot(aes(Covid_Timeline, Fatigue)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = 1, alpha = .01)
p2 <- cv %>% 
  ggplot(aes(Covid_Timeline, KESSLER6sum)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = 1, alpha = .01)
p3 <- cv %>% 
  ggplot(aes(Fatigue, KESSLER6sum)) +
  geom_point(position = position_jitter(.15, .1), shape = 1, alpha = .01) +
  geom_smooth(method = 'loess')
p1 | p2 | p3
```

```{r}
x <-cv$Covid_Timeline
m <-cv$Fatigue
y<- cv$KESSLER6sum
id <-cv$Id
m_w <-as.integer(cv$Fatigue_within*2)

dat <-data.frame(cbind(x,m,m_w, y,id))
table(dat$m_w)
```


```{r echo = TRUE}
path_m <- bf(
  m ~ x + 
    (1 |p| id)
)
path_y <- bf(
  y ~ x + mo(m_w) + 
    ( 1 |p| id)
)
f1 <- brm(
  path_m + path_y + set_rescor(FALSE),
  data = dat,
  file = here("models/mediation-k6-covid-fatigue")
)

summary(f1)
s1<-bayestestR::mediation(f1,centrality = "mean",ci=.95) # nat, no  FAT 

sjPlot::plot_model(f1)

d1<-bayestestR::describe_posterior(as.data.frame(f1),centrality = "mean", test="p_direction",ci=.95)
d1

pt1<-d1%>%
  tibble::as_tibble(include.rownames = FALSE)%>%
  dplyr::slice(n=1:10)%>%
  dplyr::select(-CI)%>%
  mutate_if(is.numeric, ~round(., 3))%>%
  ggpubr::ggtexttable(rows = NULL,
                      theme = ttheme("mRed"))

pt1
bbt18<-bayestestR::mediation(f1,centrality = "mean",ci=.95) # nat, no  FAT 


dm20<-as.data.frame(bbt20S)%>%
  dplyr::select(-proportion_mediated)%>%
  bayestestR::estimate_density()%>%
  plot(labels = FALSE)%>%
  ggpar(main = "")#+theme_solarized()
dm20
```



# ```{r}
# cv2<-cv
# cv2rr<-estimate_link(m1)
# plot(rr)
# ```




# ```{r}
# ncv<-filter(cv, yearS > 1)
# 
# m2 <- lmer(KESSLER6sum_within ~ bs(yearS ) + (1|Id), ncv)
# summary(m2)
# plot(ggeffects::ggpredict(m2, terms = "yearS[all]" ))
# ```

