---
title: "Longitudinal Effects of Pandemic Distress in New Zealand"
subtitle: "February/March 2020"
author: "Joseph Bulbulia, Psychology, Victoria University"
date: 2020-APRIL-23
bibliography: bibliography.bib
output: 
  ioslides_presentation:
    mainfont: roboto
    incremental: true
    transition: 0
    smaller: true
    css: extra.css
editor_options: 
  markdown: 
    wrap: 72
---



```{r load_libraries, include=FALSE}
# see: https://github.com/rjknell/Ioslides_css
library("tidyverse")
library("easystats")
library("patchwork")
library("kableExtra")
library("ggpubr")
#library("viridis")
#library("wesanderson")
# library("papaja")
library("here")
library("citr")
library("here")
library("brms")
library("rstan")
library("rstanarm")
# library("tidybayes")
library("lubridate")
library("ggdag")
library("viridisLite")
library("bmlm")
library("bayesplot")
library("broom")
library("purrr")
#library("cmdstanr")  #multithreading bayesian models
# rstan options
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores ())
theme_set(theme_classic())
```



```{r setup, include=FALSE}
# See: https://rstudio-pubs-static.s3.amazonaws.com/27777_55697c3a476640caa0ad2099fe914ae5.html#/
# setup
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE #,
#  layout = "l-body-outset" #,
 # fig.width= 12,
 # fig.height= 10,
#  collapse =TRUE,
#  R.options = list(width = 60)
)

```
```{r cache=TRUE}
# import data
df <- readRDS(here::here("data", "df"))
```

```{r cache = TRUE, echo = FALSE}
ord_dates_class <- c(
  "Baseline", 
  "PreCOVID", 
  "JanFeb", 
  "EarlyMarch", 
  "Lockdown",
  "PostLockdown")

# 3665 days after 30 June 2009 Saturday 13 July 2019
# 3842 days after 30 June 2009 Monday 6 January 2020
# 3895 days after 30 June 2009 Friday 28 February 2020
# 3921 days after 30 June 2009 WED MAR 25th
# 3954 days after 30 June 2009 Monday 27 April 2020
# 3672 days after June 30 2009 Saturday 20 July 2019


cv <- df %>%
  dplyr::filter(YearMeasured == 1) %>%
  dplyr::filter(Wave == 2018 | Wave == 2019) %>%
  dplyr::group_by(Id) %>% 
  filter(n() > 1) %>%
  dplyr::filter(n() != 0) %>%
  dplyr::ungroup(Id) %>%
  dplyr::mutate(Covid_Timeline =
                 # ifelse(
                 # TSCORE %in% 3837:3894,
                 # "Baseling",
                    as.factor(ifelse(
                      TSCORE %in% 3896:3921, # feb 29 - march 25th
                      "EarlyMarch",
                      ifelse(
                        TSCORE %in% 3922:3954,
                        "Lockdown", #march 26- Mon 27 April 2020
                        ifelse(
                          TSCORE > 3954, # after april 27th 20202
                          "PostLockdown",
                          ifelse(
                            TSCORE %in% 3842:3895, # jan 6 to feb 28
                            "JanFeb",
                          ifelse(
                            TSCORE %in% 3665:3841 &
                              Wave == 2019,
                            "PreCOVID",
                            "Baseline"  # 3672 TSCORE or  20 July 2019
                          )
                        )
                      )
                    ) 
                 ) ))%>%
  dplyr::mutate(PrePostCovid =
                  ifelse(
                    TSCORE > 3895, "PostLockdown",
                    ifelse(
                      TSCORE < 3895 &
                        Wave == 2019,
                      "PreCOVID",
                      "Baseline"
                    )
                  ))%>% 
  dplyr::group_by(PrePostCovid) %>% 
  filter(n() > 1) %>%
  ungroup() %>% # There is overlap between waves, we only want repeated measures 
  dplyr::select(
    TSCORE,
    WSCORE,
    Wave,
    Partner,
    Employed,
    Sat.Government,
    NZ.Business.Conditions,
    NZ.Economic.Situation,
    PrePostCovid,
    Rel.Conflict,
    Rel.Satisfaction,
    Hours.SocialMedia,
    Hours.Exercise,
    Hours.Internet,
    Hours.News,
    Hours.Family,
    Hours.Friends,
    Hours.Housework,
    Hours.Children,
    Hours.Religious,
    Hours.Work,
    Hours.Community,
    Family.Time,
    Community.Time,
    Friends.Time,
    Family.Money,
    Friends.Money,
    Community.Money,
    years,
    Id,
    Parent,
    SWB.SatPWI02, # your health
    Hours.Work,
    Hours.Exercise,
    LIFEMEANING,
    KESSLER6,
    SWB.SatPWI03, # your future security
    #  K6sum,
    KESSLER6sum,
    Age,
    Male,
    Relid,
    Pol.Orient,
    Urban,
    GenCohort,
    Edu,
    YearMeasured,
    Covid_Timeline,
    HLTH.SleepHours,
    HLTH.Fatigue,
    LIFESAT,
    PWI,
    EthnicCats,
    NZdep,
    Partner,
    Pol.Orient,
    Urban,
    Euro,
    Religious,
    NZdep,
    WSCORE,
    Religion.Church,
    Emp.JobSecure,
    Emp.JobSat,
    Emp.JobValued,
    Alcohol.Intensity,
    Alcohol.Frequency
  ) %>%
  dplyr::group_by(Id) %>% filter(n() > 1) %>%
  dplyr::filter(n() != 0) %>%
  dplyr::ungroup(Id) %>%
  dplyr::mutate(
    Urban = (Urban),
    Euro = (Euro),
    Religious = as.factor(Religious),
    Your_Health = (SWB.SatPWI02),
    Your_Future_Security = SWB.SatPWI03,
    Covid_Timeline = as.factor(Covid_Timeline)
  ) %>%
  dplyr::mutate(
    WSCORE = as.factor(WSCORE),
    EduC = scale(as.numeric(Edu), scale = F, center = TRUE),
    Sat.Government = scale(Sat.Government),
    AgeDecadeC = scale(Age, scale = F, center = T) / 10,
    Hours.Work10 = as.integer(Hours.Work) / 10,
    Hours.Sleep = as.integer(HLTH.SleepHours),
    Hours.Exercise = as.integer(Hours.Exercise),
    Fatigue = as.integer(HLTH.Fatigue),
    f_s = scale(Fatigue),
    K6sum = as.integer(KESSLER6 * 6),
    LIFEMEANING_S = scale(LIFEMEANING),
    NZdepS = scale(NZdep),
    PolOrientS = scale(Pol.Orient, scale = T, center = T),
    Relid_S = scale(Relid, scale = T, center = T),
    Conservative = Pol.Orient,
    logSM = log(Hours.SocialMedia + 1),
    logINT = log(Hours.Internet + 1),
    logEX = log(Hours.Exercise + 1),
    logWK= log(Hours.Work + 1),
    k6_s = scale(KESSLER6sum),
    Conservative_S = PolOrientS,
    Religion_Church_S = scale(Religion.Church),
    Emp.JobSecure_S = scale(Emp.JobSecure),
    KESSLER6sum = as.integer(KESSLER6sum),
    Alcohol.Intensity_S = scale(Alcohol.Intensity),
    Alcohol.Frequency_S = scale(Alcohol.Frequency),
    Hours.Work = as.integer(Hours.Work),
    Hours.Exercise = as.integer(Hours.Exercise),
    yearS = years - min(years)
  ) %>%
  dplyr::mutate(Covid_Timeline = forcats::fct_relevel(Covid_Timeline, ord_dates_class))

cv <- cbind(cv,
            demean(
              cv,
              select = c(
                "KESSLER6sum",
                "k6_s",
                "logEX",
                "logSM",
                "logINT",
                "logWK",
                "Hours.Sleep",
                "Hours.Work10",
                "Hours.Exercise",
                "Sat.Government",
                "Hours.Children",
                "Hours.Internet",
                "Hours.Friends",
                "Hours.Family",
                "Hours.Religious",
                "Hours.Community",
                "Rel.Satisfaction",
                "Rel.Conflict",
                "Family.Time",
                "Family.Money",
                "Friends.Time",
                "Friends.Money",
                "Community.Time",
                "Community.Money",
                "Fatigue",
                "Alcohol.Intensity",
                "Alcohol.Frequency",
                "NZ.Economic.Situation",
                "Emp.JobSecure",
                "Friends.Time",
                "Family.Time",
                "Community.Time",
                "Hours.SocialMedia",
                "Hours.Internet",
                "Your_Future_Security"
              ),
              group = "Id"
            )) 
# test that we only have repeated measures
# test <-cv %>%
#   group_by(Id)%>%
#   count()%>%
#   ungroup() 
```

## Plan

1. Change in indicators of psychological distress pre/post Covid
2. Mediators of psychological distress
3. Advice for future pandemics


## Data

```{r cache = TRUE}
# covid timeline
# 3665 days after 30 June 2009 Saturday 13 July 2019
# 3842 days after 30 June 2009 Monday 6 January 2020
# 3895 days after 30 June 2009 Friday 28 February 2020
# 3921 days after 30 June 2009 WED MAR 25th
library(lubridate)
library(tidyverse)


carep <- cv %>%
  dplyr::mutate(timeline = make_date(year = 2009, month = 6, day = 30) + TSCORE) %>%
  count(day = floor_date(timeline, "day")) %>%
dplyr::mutate(condition = ifelse(
    day < "2019-06-20",
    "Baseline",
    ifelse(
      day >= "2019-06-20" &
        day < "2020-01-06",
      "PreCOVID",
      ifelse(
        day >= "2020-01-06" & day < "2020-02-29",
        "Jan_Feb",
        ifelse(
          day >= "2020-02-29" & day < "2020-03-25",
          "EarlyMarch",
          ifelse(
            day >= "2020-03-25" &
              day < "2020-04-28",
            "Lockdown",
            "Postlockdown"
            )))))) %>%
  dplyr::mutate(condition = forcats::fct_relevel(condition, ord_dates_class)) %>%
  arrange(day)

# get COVID date
dates_vline0<- as.Date("2018-06-03")
dates_vline1<- as.Date("2019-06-20")
dates_vline2<- as.Date("2020-01-06")
dates_vline3<- as.Date("2020-02-28")
# get data of change of baseline
dates_vline4<- as.Date("2020-03-25")
dates_vline5 <- as.Date("2020-04-27")
dates_vline6 <- as.Date("2020-10-15")
# for line in a graph

# for line in a graph
#
dates_vline10 <- which(carep$day %in% dates_vline0)
dates_vline1b <- which(carep$day %in% dates_vline1)
dates_vline2b <- which(carep$day %in% dates_vline2)
dates_vline3b <- which(carep$day %in% dates_vline3)
dates_vline4b <- which(carep$day %in% dates_vline4)
dates_vline5b <- which(carep$day %in% dates_vline5)
dates_vline6b <- which(carep$day %in% dates_vline6)


tline <- ggplot(carep, aes(day, n)) +
  geom_col(aes(fill = condition)) + scale_x_date(date_labels = "%b/%Y", limits = c(as.Date("2018-06-10"), as.Date("2020-10-15")))  + scale_y_continuous(limits = c(0, 1000))  +
 geom_vline(xintercept = as.numeric(carep$day[dates_vline10]),
             col = "black",
             linetype = "dashed") +
  geom_vline(xintercept = as.numeric(carep$day[dates_vline1b]),
             col = "red",
             linetype = "dashed") +
  geom_vline(xintercept = as.numeric(carep$day[dates_vline2b]),
             col = "red") +
  geom_vline(xintercept = as.numeric(carep$day[dates_vline3b]),
             col = "red",
             linetype = "dashed") +
  geom_vline(xintercept = as.numeric(carep$day[dates_vline4b]),
             col = "red",
             linetype = "dashed") +
    geom_vline(xintercept = as.numeric(carep$day[dates_vline5b]),
             col = "red",
             linetype = "dashed") + 
  xlab("NZAVS Waves 10 and 11 daily counts: repeated measures") + ylab("Count of Responses")  + theme_classic() +   scale_fill_viridis_d() + theme(
    legend.position = "top",
    legend.text = element_text(size = 6),
    legend.title = element_text(color = "Black", size = 8)
  ) +
  annotate(
    "rect",
    xmin = as.Date("2018-01-03"),
    xmax = dates_vline1,
    ymin = 0,
    ymax = 1000,
    alpha = .1,
    fill = "darkblue"
  )  +
  annotate(
    "rect",
    xmin = dates_vline1,
    xmax = dates_vline6,
    ymin = 0,
    ymax = 1000,
    alpha = .001
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-07-10"),
    y = 750,
    xend = as.Date("2019-10-15"),
    yend = 800,
    curvature = -.2,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-07-10"),
    y = 750,
    xend = as.Date("2020-01-30"),
    yend = 850,
    curvature = -.2,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-07-10"),
    y = 750,
    xend = as.Date("2020-03-10"),
    yend = 875,
    curvature = -.2,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-07-10"),
    y = 750,
    xend = as.Date("2020-04-10"),
    yend = 900,
    curvature = -.2,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-07-10"),
    y = 750,
    xend = as.Date("2020-06-10"),
    yend = 925,
    curvature = -.2,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate("text",
           x = as.Date("2018-07-01"),
           y = 755,
           label = "0") +  annotate("text",
           x = as.Date("2019-10-25"),
           y = 800,
           label = "1") + 
   annotate("text",
           x = as.Date("2020-02-10"),
           y = 850,
           label = "2") + 
  annotate("text",
           x = as.Date("2020-03-15"),
           y = 875,
           label = "3") +
  annotate("text",
           x = as.Date("2020-04-20"),
           y = 900,
           label = "4") +
  annotate("text",
           x = as.Date("2020-06-10"),
           y = 925,
           label = "5")

# GRAPH
tline + plot_annotation(title = "NZAVS COVID timeline", 
subtitle = "0(34778) 1.PreCVD(23460) 2.JanFeb(2678) 3.March(2537) 4.LckDwn(1647) 5.PostLD(4456)")
```







## Mediation


```{r, layout = "l-body-outset"}
mlm_path_plot(xlab = "Condition\n(X)",
              mlab = "Mediator\n(M)",
              ylab = "Distress\n(Y)")
```


## Fatigue

```{r cache = TRUE}
library(tidyverse)
library(patchwork)
p1 <- cv %>% 
  ggplot(aes(Covid_Timeline, Fatigue)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01)+
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p2 <- cv %>% 
  ggplot(aes(Covid_Timeline, KESSLER6sum)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01)+
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p3 <- cv %>% 
  ggplot(aes(Fatigue, KESSLER6sum)) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) +
  geom_smooth(method = 'loess')
p1 | p2 | p3
```


## Relationship Conflict

```{r cache = TRUE}
p1 <- cv %>% 
  ggplot(aes(Covid_Timeline, Rel.Conflict)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p2 <- cv %>% 
  ggplot(aes(Covid_Timeline, KESSLER6sum)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) + 
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p3 <- cv %>% 
  ggplot(aes(Rel.Conflict, KESSLER6sum)) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) +
  geom_smooth(method = 'loess')
p1 | p2 | p3
```



## Your Future Security

```{r cache = TRUE}
p1 <- cv %>% 
  ggplot(aes(Covid_Timeline, Your_Future_Security)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) + 
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p2 <- cv %>% 
  ggplot(aes(Covid_Timeline, KESSLER6sum)) +
  stat_summary(fun.data = mean_cl_boot, size = 1) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) + 
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
p3 <- cv %>% 
  ggplot(aes(Your_Future_Security, KESSLER6sum)) +
  geom_point(position = position_jitter(.15, .1), shape = .5, alpha = .01) +
  geom_smooth(method = 'loess') 
p1 | p2 | p3
```



## Test

```{r pressure}
plot(pressure)
```


## next slide

```{r}
plot(pressure)
```


