---
title: "National longitudinal study reveals durable shift in public acceptance following the 2019 New Zealand Mosque Attacks"
description: |
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
date: 2021-MAR-12
output:
  distill::distill_article:
    self_contained: false
    toc: true
    code_folding: true
bibliography: bib.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  layout = "l-body-outset",
  fig.width = 12,
  fig.height = 15,
  collapse = TRUE,
  R.options = list(width = 60
  )
)
```

```{r libs, include=FALSE}
#libraries
library("here") # file management
#library("equatiomatic") # equations
library("lubridate") # working with dates
library("ggplot2") # graphs
library("ggthemes") #themes
library("ggpubr") # graphs
library("viridis") # colours
library("patchwork") # combine graphs
library("ggforce") # graphs
library("lme4") # multilevel estimation
#library("geepack") # marginal models
library("easystats") # reporting
library("kableExtra") # tables
library("broom") # working with  models
library("broom.mixed") # mixed effects models
library("brms") # bayesian estimation
library("rstan") # backend brms
library("rstanarm") # graphing
library("cmdstanr") # backend brms
library("ipw") # inverse probability weighting
library("tidybayes") # workign with posterior probability distributions
library("bayesplot") # graphs
library("ggokabeito")   # color palette
library("gghalves")     #  half geoms
library("ggbeeswarm")   # Special distribution-shaped point jittering
library("emmeans") # estimate marginal means
library("table1") # tables /now with latex
library("tidyverse") # data wrangling

# rstan options
rstan_options(auto_write = TRUE) # bayesian estimation
options(mc.cores = parallel::detectCores ()) # use all course
theme_set(theme_pubclean()) # nice theme
#theme_set(theme_classic())
```


```{}
cite_packages()
```


```{r data, cache = TRUE}
#import data
df <- readRDS(here::here("data", "df"))
```

We prepare data by selecting data from wave 2018 (years 2018-19) and wave 2019 (years 2019-20)



```{r pptimeline, cache=TRUE, fig.fullwidth = TRUE,  layout="l-body-outset", fig.width=12, fig.height=12, fig.cap="\\label{fig:pptimeline} Within-participant repeated measures covering the years before and following the attacks allow precise estimates of attitudinal change within-people (N = 11,481)."}
## timeline
rarep<-df%>%
  dplyr::filter(YearMeasured == 1) %>%
  dplyr::filter(Wave == 2018 | Wave == 2019) %>%
  dplyr::group_by(Id) %>% filter(n() == 2) %>%
  dplyr::filter(Wave == 2018 | Wave == 2019) %>%
  droplevels() %>%
  dplyr::ungroup(Id) %>%
  dplyr::mutate(timeline = make_date(year = 2009, month = 6, day = 30)+ TSCORE)%>%
  dplyr:::count(day = floor_date(timeline, "day"))%>%
  dplyr::mutate(Condition = factor(ifelse(day >="2018-06-18" & day < "2019-03-15", 0,
                                                 ifelse( day >="2019-03-15" & day < "2019-06-18",1 ,
                                                         2)),
                                                 labels= c("Control","Post-Attack", "Year following")))%>%
  arrange(day)
  #table(rarep$Condition)
# get data of change of baseline
#dates_vline1<- as.Date("2018-06-18")


# get attack date
dates_vline2<- as.Date("2019-03-15")
dates_vline3<- as.Date("2019-06-18")

# for line in a graph
dates_vline2b<-which(rarep$day %in% dates_vline2)
#dates_vline1b<-which(rarep$day %in% dates_vline1)
dates_vline3b<-which(rarep$day %in% dates_vline3)

lds2 <- ggplot(rarep, aes(day, n)) + geom_col(aes(fill = Condition)) + scale_x_date(date_labels = "%b/%Y",
                                                                                    limits = c(as.Date("2018-06-18"), as.Date("2020-10-15")))  +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  geom_vline(xintercept = as.numeric(rarep$day[dates_vline2b]),
             col = "red",
             linetype = "dashed") +
  xlab("NZAVS Waves years 2018 - 2020 daily counts by condition") + ylab("Count of Responses")+
  theme_classic() +
  # annotate(
  #   "rect",
  #   xmin = as.Date("2017-08-25"),
  #   xmax = dates_vline1,
  #   ymin = 0,
  #   ymax = 900,
  #   alpha = 0
  # ) +
  annotate(
    "rect",
    xmin = dates_vline2,
    xmax = dates_vline3,
    ymin = 0,
    ymax = 900,
    alpha = .3,
    fill = "darkred"
  ) +
  # annotate(
  #   "rect",
  #   xmin = dates_vline1,
  #   xmax = dates_vline2,
  #   ymin = 0,
  #   ymax = 900,
  #   alpha = .3
  # ) +
  annotate(
    "rect",
    xmin = dates_vline3,
    xmax = as.Date("2020-10-15"),
    ymin = 0,
    ymax = 900,
    alpha = .05,
    fill = "red"
  ) +
  annotate(
    "text",
    x = as.Date("2018-10-15"),
    y = 1500,
    label = "Wave 10\npre-attacks"
  ) +
  # annotate(
  #   "text",
  #   x = as.Date("2018-01-15"),
  #   y = 980,
  #   label = "Wave 9
  #          baseline (control)"
  # ) +
  annotate(
    "text",
    x = as.Date("2019-05-15"),
    y = 1500,
    label = "Wave 10\npost\nattacks"
  ) +
  annotate(
    "text",
    x = as.Date("2020-02-15"),
    y = 1500,
    label = "Wave 11\nrepeated"
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-02-15"),
    y = 950,
    xend = as.Date("2018-10-15"),
    yend = 950,
    curvature = -.3,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(
    geom = "curve",
    x = as.Date("2018-02-15"),
    y = 950,
    xend = as.Date("2019-05-15"),
    yend = 950,
    curvature = -.3,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate("text",
           x = as.Date("2018-11-05"),
           y = 950,
           label = "Control") +
  annotate(
    geom = "curve",
    x = as.Date("2019-05-15"),
    y = 1000,
    xend = as.Date("2020-05-15"),
    yend = 1000,
    curvature = -.3,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate("text",
           x = as.Date("2019-06-05"),
           y = 950,
           label = "Attack") +
  annotate("text",
           x = as.Date("2020-07-30"),
           y = 1000,
           label = "Year\nFollowing") +
  annotate(
    geom = "curve",
    x = as.Date("2018-11-15"),
    y = 1000,
    xend = as.Date("2020-05-15"),
    yend = 1000,
    curvature = -.3,
    arrow = arrow(length = unit(2, "mm"))
  ) +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 6),
    legend.title = element_text(color = "Black", size = 8)
  ) +
  scale_fill_viridis_d(option = "plasma")

### USE GRAPH OF TIMELINE
lds2


ggsave(
  lds2,
  path = here::here(here::here("_posts", "mus", "figs")),
  width = 10,
  height = 5,
  units = "in",
  filename = "timeline.jpg",
  device = 'jpeg',
  limitsize = FALSE,
  dpi = 1200
)
```

```{r}
## For intro
p1pp <- plot(p1,
            add.data = TRUE,
            dot.alpha = .05,
            jitter = .8) +
  ylab("Warmth to Muslims (1-7)") + labs(title = "Warm Muslims") +
  geom_hline(yintercept = 4.395, color = "green") +
  # scale_y_continuous(limits = c(1, 7)) +
  scale_colour_viridis_d() + xlab("Attack timeline") +
  # geom_vline(xintercept = c(2.8), colour = "red", linetype = "dashed") +
  theme_classic()
```


<!-- ## Weights graph  -->

<!-- ```{r} -->
<!-- kn <- km4 -->
<!-- kn$attack <- as.numeric(km4$Attack) -->
<!-- kn$attack -->



<!-- imputed1<-imputed$imputations$imp1 -->
<!-- im<- imputed1 -->
<!-- im$attack <- as.numeric(im$As)-1 -->
<!-- im$warmth <- as.numeric(im$Ys) -->
<!-- kn$warmth <- as.numeric(kn$Warm.Muslims) -->
<!-- im$attack -->

<!-- kn%>% -->
<!--   filter(Wave ==2019 & As ==1) %>% -->
<!--   select(Warm.Muslims) %>% -->
<!--   count(is.na(.)) -->

<!-- plot1 <- ggplot() +  -->
<!--     geom_histogram(data = filter(im, attack == 1 & Wave == 2018),  -->
<!--             #  bins = 10,  -->
<!--               aes(x = warmth),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.55)) +   -->
<!--   geom_histogram(data = filter(im, attack == 0 & Wave == 2018),  -->
<!--                 # bins = 10,  -->
<!--                  aes(x = warmth, y = -..count..), -->
<!--                   fill = colorspace::lighten("deepskyblue4", 0.55))  + -->
<!--   geom_histogram(data = filter(kn, attack == 1& Wave == 2018),  -->
<!--                  #bins = 10,  -->
<!--                  aes(x = warmth),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.1))+  -->
<!--   geom_histogram(data = filter(kn, attack == 0 & Wave == 2018),  -->
<!--                 # bins = 10,  -->
<!--                  aes(x = warmth, y = -..count..), -->
<!--                  fill = colorspace::lighten("deepskyblue4", 0.1)) + -->
<!--  annotate(geom = "label", x = 1.5, y = 2000, label = "Exposed\nobserved", -->
<!--          fill = colorspace::lighten("chocolate",.1), color = "white", hjust = 1) + -->
<!--  annotate(geom = "label", x = 3.5, y = 5000, label = "Exposed\nimputed", -->
<!--            fill = colorspace::lighten("chocolate",.35), color = "white", hjust = 1)+ -->
<!--  annotate(geom = "label", x = 1.5, y = -4000, label = "Not Exposed\nobserved", -->
<!--          fill = colorspace::lighten("deepskyblue4", 0.1), color = "white", hjust = 1) + -->
<!--  annotate(geom = "label", x = 3.5, y = -10000, label = "Not Exposed\nimputed", -->
<!--           fill = colorspace::lighten("deepskyblue4",  .35), color = "white", hjust = 1) + -->
<!--  geom_hline(yintercept = 0, color = "white", size = 0.25) + -->
<!--  scale_y_continuous(label = abs) +  -->
<!--     scale_y_continuous(limits=c(-15000,15000)) + -->
<!--  # coord_cartesian(xlim = c(0.1, 1)) + -->
<!--   labs(x = "Warmth to Muslim", y = "Counts") + labs(title= "Wave 10") -->


<!-- plot1 -->

<!-- length(unique(kn$Id)) -->
<!-- length(unique(imputed1$Id)) -->

<!-- plot2 <- ggplot() +  -->
<!--     geom_histogram(data = filter(im, attack == 1 & Wave == 2019),  -->
<!--              # bins = 10,  -->
<!--               aes(x = warmth),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.55)) +   -->
<!--   geom_histogram(data = filter(im, attack == 0 & Wave == 2019),  -->
<!--                 # bins = 10,  -->
<!--                  aes(x = warmth, y = -..count..), -->
<!--                   fill = colorspace::lighten("deepskyblue4", 0.55))  + -->
<!--   geom_histogram(data = filter(kn, attack == 1 & Wave == 2019),  -->
<!--                  #bins = 10,  -->
<!--                  aes(x = warmth),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.1))+  -->
<!--   geom_histogram(data = filter(kn, attack == 0 & Wave == 2019),  -->
<!--                #  bins = 10,  -->
<!--                  aes(x = warmth, y = -..count..), -->
<!--                  fill = colorspace::lighten("deepskyblue4", 0.1)) + -->
<!--  annotate(geom = "label", x = 3.5, y = 8000, label = "Exposed\nobserved", -->
<!--          fill = colorspace::lighten("chocolate",.1), color = "white", hjust = 1) + -->
<!--  annotate(geom = "label", x = 3.5, y = 12000, label = "Exposed\nimputed", -->
<!--            fill = colorspace::lighten("chocolate",.35), color = "white", hjust = 1)+ -->
<!--  annotate(geom = "label", x = 2.5, y = -4000, label = "Not Exposed is\nfully imputed", -->
<!--           fill = colorspace::lighten("deepskyblue4",  .35), color = "white", hjust = 1) + -->
<!--  geom_hline(yintercept = 0, color = "white", size = 0.25) + -->
<!--  scale_y_continuous(label = abs) +  -->
<!--  # coord_cartesian(xlim = c(0.1, 1)) + -->
<!--   labs(x = "Warmth to Muslim", y = "Counts") + labs(title= "Wave 11") +  -->
<!--   scale_y_continuous(limits=c(-15000,15000)) -->
<!-- plot2 -->
<!-- imp_frq<- plot1 + plot2 + plot_annotation(tag_levels = "a", title = "Comparison of multiply-imputed responses and observed\nresponse distributions in Wave 10 and Wave 11") -->


<!-- imp_frq -->


<!-- ggsave( -->
<!--   imp_frq, -->
<!--   path = here::here(here::here("_posts", "mus", "figs")), -->
<!--   width = 12, -->
<!--   height = 8, -->
<!--   units = "in", -->
<!--   filename = "imp_frq.jpg", -->
<!--   device = 'jpeg', -->
<!--   limitsize = FALSE, -->
<!--   dpi = 1200 -->
<!-- ) -->



<!-- model_treatment_freq <- glm(attack ~    Male  + Edu + EthnicCats + Religious + Pol.Orient + Urban + NZdep + Religious,  data = kn,family = binomial(link = "logit")) -->


<!-- # Step 2: Use the treatment model to calculate propensity scores, and -->
<!-- # Step 3: Use the propensity scores to calculate inverse probability of treatment weights -->
<!-- km_with_weights <- augment(model_treatment_freq, kn, -->
<!--                              type.predict = "response") %>% -->
<!--   rename(propensity = .fitted) %>%  -->
<!--   mutate(iptw = (attack / propensity) + ((1 - attack) / (1 - propensity))) -->


<!-- max(km_with_weights$iptw) -->


<!-- # Step 4: Use the IPTWs in a model that estimates the effect of treatment on outcome -->
<!-- model_outcome_freq <- lm(Warm.Muslims ~ Attack   , -->
<!--                          data = km_with_weights, -->
<!--                          weights = iptw) -->

<!-- # Coefficient  -->
<!-- tidy(model_outcome_freq) -->




<!-- library(MetBrewer) -->
<!-- # ggplot() +  -->
<!-- #   geom_histogram(data = filter(km, Attack == 1),  -->
<!-- #                  bins = 50, aes(x = ipw),  -->
<!-- #                  fill = colorspace::lighten("darkorange", 0.5)) +  -->
<!-- #    geom_histogram(data = filter(km, Attack == 0),  -->
<!-- #                  bins = 50, aes(x = ipw, y = -..count..), -->
<!-- #                  fill = colorspace::lighten("darkgreen", 0.5)) + -->
<!-- #   geom_hline(yintercept = 0) +  -->
<!-- #   annotate(geom = "label", x = 0.8, y = 2000, label = "Treated",  -->
<!-- #            fill = colorspace::lighten("darkorange", 0.2), color = "white", hjust = 0) + -->
<!-- #   annotate(geom = "label", x = 0.8, y = -2000, label = "Untreated",  -->
<!-- #            fill = colorspace::lighten("darkgreen", 0.2), color = "white", hjust = 0) + -->
<!-- #   scale_y_continuous(label = abs) + -->
<!-- #  #coord_cartesian(xlim = c(0.1, 0.8), ylim = c(-10000, 10000)) + -->
<!-- #   labs(x = "Propensity", y = "Count")  -->


<!-- #   -->
<!-- imputed -->
<!-- ipwplot <- ggplot() +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.55)) +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw, y = -..count..), -->
<!--                   fill = colorspace::lighten("deepskyblue4", 0.55)) + -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.1)) +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, y = -..count..), -->
<!--                  fill = colorspace::lighten("deepskyblue4", 0.1)) + -->
<!--  annotate(geom = "label", x = 0.7, y = 1000, label = "Treated (actual)", -->
<!--          fill = colorspace::lighten("chocolate",.1), color = "white", hjust = 1) + -->
<!--  annotate(geom = "label", x = 0.7, y = 3000, label = "Treated (imputed\npseudo-population)", -->
<!--            fill = colorspace::lighten("chocolate",.35), color = "white", hjust = .5)+ -->
<!--  annotate(geom = "label", x = 0.7, y = -1000, label = "Untreated (actual)", -->
<!--          fill = colorspace::lighten("deepskyblue4", 0.1), color = "white", hjust = 1) + -->
<!--  annotate(geom = "label", x = 0.7, y = -3000, label = "Untreated (imputed\npseudo-population)", -->
<!--           fill = colorspace::lighten("deepskyblue4",  .35), color = "white", hjust = 1) + -->
<!--  geom_hline(yintercept = 0, color = "white", size = 0.25) + -->
<!--  scale_y_continuous(label = abs) +  -->
<!--  # coord_cartesian(xlim = c(0.1, 1)) + -->
<!--   labs(x = "Propensity", y = "Count") + labs(title= "Comparison of propensity score\nand original response distributions") -->
<!-- ipwplot -->



<!-- model_treatment_freq <- glm(attack ~   -->
<!--                               Male  + Edu + EthnicCats + Religious + Pol.Orient + Urban + NZdep + Religious, -->
<!--                             data = kp18,family = binomial(link = "logit")) -->


<!-- # Step 2: Use the treatment model to calculate propensity scores, and -->
<!-- # Step 3: Use the propensity scores to calculate inverse probability of treatment weights -->
<!-- km_with_weights <- augment(model_treatment_freq, kp18, -->
<!--                              type.predict = "response") %>% -->
<!--   rename(propensity = .fitted) %>%  -->
<!--   mutate(iptw = (attack / propensity) + ((1 - attack) / (1 - propensity))) -->


<!-- max(km_with_weights$iptw) -->


<!-- # Step 4: Use the IPTWs in a model that estimates the effect of treatment on outcome -->
<!-- model_outcome_freq <- lm(Warm.Muslims ~ Attack , -->
<!--                          data = km_with_weights, -->
<!--                          weights = iptw) -->

<!-- # Coefficient  -->
<!-- tidy(model_outcome_freq) -->




<!-- library(MetBrewer) -->
<!-- # ggplot() +  -->
<!-- #   geom_histogram(data = filter(km, Attack == 1),  -->
<!-- #                  bins = 50, aes(x = ipw),  -->
<!-- #                  fill = colorspace::lighten("darkorange", 0.5)) +  -->
<!-- #    geom_histogram(data = filter(km, Attack == 0),  -->
<!-- #                  bins = 50, aes(x = ipw, y = -..count..), -->
<!-- #                  fill = colorspace::lighten("darkgreen", 0.5)) + -->
<!-- #   geom_hline(yintercept = 0) +  -->
<!-- #   annotate(geom = "label", x = 0.8, y = 2000, label = "Treated",  -->
<!-- #            fill = colorspace::lighten("darkorange", 0.2), color = "white", hjust = 0) + -->
<!-- #   annotate(geom = "label", x = 0.8, y = -2000, label = "Untreated",  -->
<!-- #            fill = colorspace::lighten("darkgreen", 0.2), color = "white", hjust = 0) + -->
<!-- #   scale_y_continuous(label = abs) + -->
<!-- #  #coord_cartesian(xlim = c(0.1, 0.8), ylim = c(-10000, 10000)) + -->
<!-- #   labs(x = "Propensity", y = "Count")  -->


<!-- #   -->
<!-- imputed -->
<!-- ipwplot <- ggplot() +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.55)) +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw, y = -..count..), -->
<!--                   fill = colorspace::lighten("deepskyblue4", 0.55)) + -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.1)) +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, y = -..count..), -->
<!--                  fill = colorspace::lighten("deepskyblue4", 0.1)) + -->
<!--   # annotate(geom = "label", x = 0.7, y = 1000, label = "Treated (actual)",  -->
<!--   #         fill = colorspace::lighten("chocolate",.1), color = "white", hjust = 1) + -->
<!--   # annotate(geom = "label", x = 0.7, y = 3000, label = "Treated (imputed\npseudo-population)",  -->
<!--   #           fill = colorspace::lighten("chocolate",.35), color = "white", hjust = .5)+ -->
<!--   # annotate(geom = "label", x = 0.7, y = -1000, label = "Untreated (actual)",  -->
<!--   #         fill = colorspace::lighten("deepskyblue4", 0.1), color = "white", hjust = 1) + -->
<!--   # annotate(geom = "label", x = 0.7, y = -3000, label = "Untreated (imputed\npseudo-population)",  -->
<!--   #          fill = colorspace::lighten("deepskyblue4",  .35), color = "white", hjust = 1) + -->
<!--   # geom_hline(yintercept = 0, color = "white", size = 0.25) + -->
<!--   # scale_y_continuous(label = abs) + -->
<!--  # coord_cartesian(xlim = c(0.1, 0.8), ylim = c(-80, 100)) + -->
<!--   labs(x = "Propensity", y = "Count") + labs(title= "Comparison of propensity score\nand original response distributions") -->
<!-- ipwplot -->





<!-- model_treatment_freq <- glm(attack ~   -->
<!--                               Male  + Edu + EthnicCats + Religious + Pol.Orient + Urban + NZdep + Religious, -->
<!--                             data = kp19,family = binomial(link = "logit")) -->


<!-- # Step 2: Use the treatment model to calculate propensity scores, and -->
<!-- # Step 3: Use the propensity scores to calculate inverse probability of treatment weights -->
<!-- km_with_weights <- augment(model_treatment_freq, kp19, -->
<!--                              type.predict = "response") %>% -->
<!--   rename(propensity = .fitted) %>%  -->
<!--   mutate(iptw = (attack / propensity) + ((1 - attack) / (1 - propensity))) -->


<!-- min(km_with_weights$iptw) -->


<!-- # Step 4: Use the IPTWs in a model that estimates the effect of treatment on outcome -->
<!-- model_outcome_freq <- lm(Warm.Muslims ~ Attack , -->
<!--                          data = km_with_weights, -->
<!--                          weights = iptw) -->

<!-- # Coefficient  -->
<!-- tidy(model_outcome_freq) -->





<!-- ind <- imputed1 -->
<!-- ind$propensity<- rep(1,nrow(ind)) -->
<!-- ind$iptw<- rep(1,nrow(ind)) -->
<!-- ind$attack <- ind$As -->

<!-- ipwplot <- ggplot() +  -->
<!--   geom_histogram(data = filter(ind, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.55)) +  -->
<!--   geom_histogram(data = filter(ind, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, weight = iptw, y = -..count..), -->
<!--                   fill = colorspace::lighten("deepskyblue4", 0.55)) + -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 1),  -->
<!--                  bins = 50, aes(x = propensity),  -->
<!--                  fill = colorspace::lighten("chocolate", 0.1)) +  -->
<!--   geom_histogram(data = filter(km_with_weights, attack == 0),  -->
<!--                  bins = 50, aes(x = propensity, y = -..count..), -->
<!--                  fill = colorspace::lighten("deepskyblue4", 0.1)) + -->
<!--  #  annotate(geom = "label", x = 0.7, y = 1000, label = "Treated (actual)",  -->
<!--  #          fill = colorspace::lighten("chocolate",.1), color = "white", hjust = 1) + -->
<!--  #  annotate(geom = "label", x = 0.7, y = 3000, label = "Treated (IPTW\npseudo-population)",  -->
<!--  #            fill = colorspace::lighten("chocolate",.35), color = "white", hjust = 1)+ -->
<!--  #  annotate(geom = "label", x = 0.7, y = -1000, label = "Untreated (actual)",  -->
<!--  #          fill = colorspace::lighten("deepskyblue4", 0.1), color = "white", hjust = 1) + -->
<!--  #  annotate(geom = "label", x = 0.7, y = -3000, label = "Untreated (IPTW\npseudo-population)",  -->
<!--  #           fill = colorspace::lighten("deepskyblue4",  .35), color = "white", hjust = 1) + -->
<!--  #  geom_hline(yintercept = 0, color = "white", size = 0.25) + -->
<!--  #  scale_y_continuous(label = abs) + -->
<!--  # # coord_cartesian(xlim = c(0.1, 0.8), ylim = c(-80, 100)) + -->
<!--    labs(x = "Propensity", y = "Count") + labs(title= "Comparison of propensity score\nand original response distributions")#+ scale_y_continuous(limits=c(-15000,15000)) -->
<!-- ipwplot -->



<!-- ggsave( -->
<!--   ipwplot, -->
<!--   path = here::here(here::here("_posts", "mus", "figs")), -->
<!--   width = 10, -->
<!--   height = 5, -->
<!--   units = "in", -->
<!--   filename = "ipweightplot.jpg", -->
<!--   device = 'jpeg', -->
<!--   limitsize = FALSE, -->
<!--   dpi = 1200 -->
<!-- ) -->


<!-- ``` -->


## MI

```{r}
library(tidyverse)


### ALL
str(datlist)

library(tidyverse)
km_all <- df %>%
  dplyr::select(
    Id,
    Age,
    Wave,
    EthnicCats,
    Employed,
    Urban,
    Edu,
    Male,
    Pol.Orient,
    NZdep,
    Religious,
    GenCohort,
    Urban,
    TSCORE,
    Partner,
    Parent,
    # Warm.Overweight,
    # Warm.Elderly,
    # Warm.MentalIllness,
    Warm.Muslims,
    # Warm.Immigrants,
    # Warm.Asians,
    # Warm.Refugees,
    # Wave,
    # Warm.Maori,
    # Warm.NZEuro,
    # Warm.Indians,
    # Warm.Chinese,
    # Warm.Refugees,
    # Warm.Pacific,
    YearMeasured
  ) %>%
  dplyr::filter(Wave == 2018 | Wave ==2019) %>%
  droplevels() %>%
  dplyr::mutate(org2018 =  ifelse(Wave == 2018 & YearMeasured ==1,1,0 ))%>%
  group_by(Id) %>%
  dplyr::mutate(hold = mean(org2018, na.rm = TRUE)) %>%  # Hack
  filter(hold>0) %>% # hack!
    ungroup(Id) %>%
  dplyr::mutate(Edu = as.numeric(Edu))%>%
  arrange(Wave,Id) %>%
  dplyr::mutate(Attack = as.numeric((ifelse(
    (TSCORE >= 3545 & Wave == 2018)|(Wave==2019), 1, 0)))) %>% # All 2019s even if NA need to be 1
 # dplyr::filter(Attack == 0) %>%
  dplyr::mutate(dys = (TSCORE - min(TSCORE)))%>% 
  dplyr::mutate(Ys = Warm.Muslims, 
                As = Attack)%>%
  dplyr::mutate(yrs =  (dys/365))%>% 
  dplyr::mutate(wave = as.numeric(Wave)-1) %>% 
  select(Id, Wave, Ys, As, Warm.Muslims, Attack, Age, EthnicCats, Edu, Employed, Urban, Male, GenCohort, Religious, Pol.Orient, Parent, Partner, Urban, NZdep,wave) %>%
  group_by(Id)%>%
  dplyr::mutate(pol_bz = if_else(Wave == "2018", (Pol.Orient), NA_real_)) %>%
  fill(pol_bz) %>%
  dplyr::mutate(rel_bz = if_else(Wave == "2018", (as.numeric(Religious)), NA_real_)) %>%
  fill(rel_bz) %>%
  dplyr::mutate(partner_bz = if_else(Wave == "2018", (as.numeric(Partner)), NA_real_)) %>%
  fill(partner_bz) %>%
  dplyr::mutate(parent_bz = if_else(Wave == "2018", (as.numeric(Parent)), NA_real_)) %>%
  fill(parent_bz) %>%
  dplyr::mutate(age_bz = if_else(Wave == "2018", (Age), NA_real_)) %>%
  fill(age_bz) %>%
    dplyr::mutate(nzdep_bz = if_else(Wave == "2018", (NZdep), NA_real_)) %>%
  fill(nzdep_bz) %>%
  dplyr::mutate(male_2z = if_else(Wave == "2018", (as.numeric(Male))/2, NA_real_)) %>%
  fill(male_2z) %>%
  dplyr::mutate(employed_bz = if_else(Wave == "2018", (as.numeric(Employed)), NA_real_)) %>%
  fill(employed_bz) %>%
  dplyr::mutate(edu_bz = if_else(Wave == "2018", (Edu), NA_real_)) %>%
  fill(edu_bz) %>%
  dplyr::mutate(ubran_bz = if_else(Wave == "2018", (as.numeric(Urban)), NA_real_)) %>%
  fill(ubran_bz) %>%
  dplyr::mutate(EthnicCats_b = if_else(Wave == "2018", as.numeric(EthnicCats), NA_real_)) %>%
  fill(EthnicCats_b) %>% 
  dplyr::mutate(EthnicCats_b, as.factor(EthnicCats_b)) %>%
  ungroup()%>%
  arrange(Id,Wave) 

length(unique(km_all$Id))
km_all
head(km_all[,12:25])
# correct
table1::table1(~ Warm.Muslims|Wave*as.factor(Attack), data = km_all, overall=FALSE)


obtl<-table1::table1(~ Attack|Wave, data = km_all, overall=FALSE)
kable(obtl, format ="latex", booktabs = TRUE)


x <- table1::table1(~ Warm.Muslims + Age + Male + GenCohort + Edu + Employed + EthnicCats  +  Religious + Pol.Orient + NZdep + Urban|Wave*As, data = km_all, overall=FALSE)
x
t1kable(x, format ="latex")



# create new data set
library(tidyverse)
kf  <- km_all %>%
  group_by(Id) %>%  # All ZEROS
 # mutate(Attack == as.numeric(Attack))%>%
  mutate(As = (ifelse(Wave==2018 & Attack == 1|Wave == 2019, 0, 
                     ifelse(Wave==2018 & Attack == 0, 1, Attack)))) %>%
  mutate(Ys = ifelse(Wave==2018 & Attack == 1|Wave ==2019, NA, 
                     ifelse(Wave==2018 & Attack == 0, NA, Warm.Muslims)))%>%
  ungroup() %>%
  arrange(Wave,Id) 


  
# Test  = Correct
table1::table1(~Ys|Wave *as.factor(As), data =kf ,overall=F)



## Bind - double dataset to creat missing values
ka <- km_all %>%
bind_rows(kf)%>%
  arrange(Id,Wave) %>%
  mutate(As = as.factor(As)) %>%
  select(-c(Warm.Muslims,Attack))

head(ka)
ka
# Check 
table1::table1( ~Ys | Wave*As, data = ka)

# impute missing data

# avoid collineraity
ka2<-ka%>%
  select(Id,Wave,wave,As,Ys,pol_bz,rel_bz,partner_bz,parent_bz,age_bz,nzdep_bz,male_2z,employed_bz,edu_bz,ubran_bz,EthnicCats_b)

ka2<-as.data.frame(ka2) 


### WITHOUT JOINT ASSUMPTION 
# filter only 0s and only 1s for the As
d0 <- ka2 %>%
  filter(As==0 )

d18 <- ka2 %>%
  filter(As==1 & Wave ==2018)

# need full distribution to obtain correct marginal for 19 = 1 (because we have 2018=0, and 2018=1)
d19 <- ka2 



#ka3$Wave<-as.numeric(ka3$Wave)

library(Amelia)
d0 <-as.data.frame(d0)

head(d0)
imputed_0<- amelia(
  set.seed=1234,
  d0, #dataset to impute
  cs= c("Id"),
  ts= c("wave"),
  m = 10, # number of imputations
  noms = c(
    "EthnicCats_b"
  ),
   idvars=c("Wave","As")) #, # do 

head(d0)



d18<-as.data.frame(d18)

imputed_18<- amelia(
  d18, #dataset to impute
  m = 10, # number of imputations
  noms = c(
    "EthnicCats_b"
  ),
   idvars=c("Wave","As","Id","wave")) #, # do 



d19<-as.data.frame(d19)
imputed_19<- amelia(
  set.seed=14321,
  d19, #dataset to impute
  m = 10, # number of imputations
 cs= c("Id"),
 ts= c("wave"),
  noms = c(
    "EthnicCats_b"
  ),
   idvars=c("Wave","As")) # correct

datlist
# filter only the 2019 

m<-10
imputed_19s<-NULL

for(i in 1:m) {
  imputed_19s$imputations$imp[[i]] <- imputed_19$imputations[[i]] %>%
    dplyr::filter(Wave == 2019 & As == 1) %>%
    arrange(Wave, Id)
}

 tail(imputed_0$imputations$imp1)
 
 imputed_19s$imputations$imp[[1]]
 
 
m<-10
imps <-NULL
for(i in 1:m) {
  imps$imputations$imp[[i]] <- dplyr::bind_rows(imputed_0$imputations[[i]], 
                                     imputed_18$imputations[[i]],
                                     imputed_19s$imputations$imp[[i]])
  imps$imputations$imp[[i]] <- imps$imputations$imp[[i]] %>% arrange(Wave,Id)
}

# 
# m<-20
# imps<-NULL
# for(i in 1:m) {
#   imps$imputations$imp[[i]] <- dplyr::bind_rows(imputed_0$imputations[[i]], 
#                                      imputed_1$imputations[[i]])
#   imps$imputations$imp[[i]] <- imps$imputations$imp[[i]] %>% arrange(Wave,Id)
#   
# }

 
 
m<-10
impsL <-NULL
datlist <- NULL

for(i in 1:m) {
  impsL$imputations[[i]]<- as.data.frame(imps$imputations$imp[[i]])
}

# datlist <- impsL$imputations
# saveRDS(datlist, here::here("_posts", "mus", "mods", "datlist"))
# saveRDS(impsL, here::here("_posts", "mus", "mods", "imps"))
# saveRDS(imps, here::here("_posts", "mus", "mods", "imps"))


tscsPlot(imputed, var = "Ys", cs =c(2,4,491,564,76,582), draws = 100, conf = 0.9, misscol = "red",
  obscol = "black")


m<-10
models1<-NULL
for(i in 1:m) {
  models1[[i]] <- lmer(Ys ~ As * Wave  + (1|Id), data=impsL$imputations[[i]])
}

pool_parameters(models1)
pred1<- ggeffects::ggemmeans(models1[[2]], terms = c("Wave","As"))
plot(pred1)







library(Amelia)
# see: https://www.andrewheiss.com/blog/2018/03/07/amelia-tidy-melding/, who writes:
# unclass() is necessary because bind_rows() will complain when dealing with
# lists with the "amelia" class, which is what amelia() returns



all_imputations <- bind_rows(unclass(imputed$imputations), .id = "m") %>%
  group_by(m) %>%
  nest()

all_imputations <- bind_rows(unclass(imps$imputations), .id = "m") %>%
  group_by(m) %>%
  nest()

unnest(all_imputations) %>%
  select(m, Wave, As,Ys )%>%
   arrange((m), Wave) %>%
   group_by(m,Wave,As) %>%
  rename( Dataset = m,
          Muslim_Warmth = Ys,
          Exposure = As) %>%
   summarise(mean = mean(Muslim_Warmth), sd = sd(Muslim_Warmth) )%>%
  pivot_wider(names_from = c("Exposure","Wave"), values_from = c(mean,sd))%>%
  mutate( across(where(is.numeric), round, 3)) 
%>%
   kbl("latex",booktabs =T, caption = "Imputed mean/sd for warmth to Muslims by condition and wave")
           
   
unnest(all_imputations) %>%
  select(m, Wave, As,Ys )%>%
   group_by(Wave,As) %>%
  rename( Dataset = m,
          Muslim_Warmth = Ys,
          Exposure = As) %>%
   summarise(n = n(), mean = mean(Muslim_Warmth), sd = sd(Muslim_Warmth) )%>%
  mutate( across(where(is.numeric), round, 3)) %>%
   kbl("latex",booktabs =T, caption = "Overall imputed mean/sd for warmth to Muslims by condition and wave")


# This doesn't work
# all_imputations_d <- bind_rows(unclass(imputed_d$imputations), .id = "m") %>%
#   group_by(m) %>%
#   nest()
# 
# unnest(all_imputations_d) %>%
#   select(m, Wave, As,Ys )%>%
#    group_by(Wave,As) %>%
#   rename( Dataset = m,
#           Muslim_Warmth = Ys,
#           Exposure = As) %>%
#    summarise(n = n(), mean = mean(Muslim_Warmth), sd = sd(Muslim_Warmth) )%>%
#   mutate( across(where(is.numeric), round, 3)) %>%
#    kbl("latex",booktabs =T, caption = "Overall imputed mean/sd for warmth to Muslims by condition and wave")

unnest(all_imputations_d) %>%
  select(m, Wave, As,Ys )%>%
   arrange((m), Wave) %>%
   group_by(m,Wave,As) %>%
  rename( Dataset = m,
          Muslim_Warmth = Ys,
          Exposure = As) %>%
   summarise(mean = mean(Muslim_Warmth), sd = sd(Muslim_Warmth) )%>%
  pivot_wider(names_from = c("Exposure","Wave"), values_from = c(mean,sd))%>%
  mutate( across(where(is.numeric), round, 3)) 
```

## FULL BAYES



```{r}
## FULL BAYES
datlist<-readRDS(here::here("_posts","mus","mods","datlist"))
datlist

m_us <- brms::brm( 
  Ys ~ As *  Wave + (1|Id), 
  data = imputed1, 
  seed = 1234,
  warmup = 1000,
  iter = 2000,
  chains = 4,
  backend = "cmdstanr",
  file = here::here("_posts", "mus", "mods", "m_us.rds"))

lazerhawk::brms_SummaryTable(m_us)
prior_summary(m_us)

# Print Table
ouput <- tidy(m_us)
str(ouput)
ouput
#output<- as.data.frame(ouput)


library(lazerhawk)
blh_tab <- brms_SummaryTable(m_us, panderize=F)
blh_tab
blh_tab %>%
   kable(booktabs = T, "latex", caption =  "Parameter for effect of attack on warmth to Muslims") %>%
    print()



## prior = c(prior(normal(0, 1), class = b)),

#amelia.list<-readRDS(here::here("_posts","mus", "mods", "amelia.list"))

```


### Graphs 

```{r}
#### BRMS MODEL

marg_eff_attack_0a <- m_us %>%
  epred_draws(newdata = expand.grid(As = c(0, 1),Wave = c("2018", "2019")),
              re_formula =NA)
           #   re_formula = NULL)  # or re_formula = ~ (1 | region)

saveRDS(marg_eff_attack_0a,  here::here("_posts", "mus", "mods", "marg_eff_attack_0a.rds"))
marg_eff_attack_0a <- readRDS(here::here("_posts", "mus", "mods", "marg_eff_attack_0a.rds"))

#marg_eff_attack_0a
# Obtain contrasts
# marg_eff_attack_0a<- marg_eff_attack_0a%>%
#   filter(As == 1 & Wave ==2019) #Attack == 1 & Wave ==2018|  Attack == 0 & Wave ==2018)

# marg_eff_attack_0
plot_all <- ggplot(
  marg_eff_attack_0a,
  aes(
    x = .epred,
    y = Wave,
    fill = as.factor(As)
  ) ) + 
#  scale_y_discrete(limits=rev) +
    stat_halfeye() +
    scale_fill_okabe_ito() +
    labs(
      x = "Predicted Warmth Response",
      y = "w2018(years 2018-2019); w2019 (years 2019-2020)",
      fill = "Conterfactual Contrasts",
      subtitle = "Bayesian posterior locations of potential outcomes"
    ) +
  #  scale_x_continuous(limits=c(4.0,4.6)) +
    theme_pubclean() +
    theme(legend.position = "bottom"
    )
plot_all
#plot_all


# not working
grand_mean_ame_a <- m_us %>%
  emmeans(~ As*Wave,
          epred = TRUE, re_formula = NA) %>%
  contrast() %>%
  gather_emmeans_draws() 

grand_mean_ame_a
#   filter(As == 1 & Wave ==2019) #Attack == 1 & Wave ==2018|  Attack == 0 & Wave ==2018)

#saveRDS(grand_mean_ame_a,  here::here("_posts", "mus", "mods", "grand_mean_ame_a.rds"))
#grand_mean_ame_a <- readRDS(here::here("_posts", "mus", "mods", "grand_mean_ame_a.rds"))

# remove erro contrasts / we don't observe 0 in year two 




plot_all__ame <- ggplot(grand_mean_ame_a,
                                     aes(x = .value)) +
  stat_halfeye(slab_alpha = 0.75, fill = "grey") +
  scale_fill_okabe_ito(order = c(3, 4)) +
  labs(x = "Average marginal effect of attack on warmth to Muslims",
       y = "Density") +
  #facet_wrap(vars(region)) +
  theme_classic() + 
  theme(legend.position = "bottom") + labs(title= "Marginal effect of attack on warmth to Muslims")
plot_all__ame 
# Try
library(patchwork)
bayes_plots_a <- plot_all + plot_all__ame + plot_annotation(tag_levels = 'a')
bayes_plots_a

ggsave(
  bayes_plots_a,
  path = here::here(here::here("_posts", "mus", "figs")),
  width = 10,
  height = 5,
  units = "in",
  filename = "bayes_plots_a.jpg",
  device = 'jpeg',
  limitsize = FALSE,
  dpi = 1200
)


# 
# blh_tab %>%
#    kable(booktabs = T, "latex", caption =  "Parameter for effect of attack on warmth to Muslims") %>%
#     print()
```

## MI Bayes

```{r}
## Run on my other mac, cmdstanr was ausing problems
gc()

plot_bayes <- m_us %>%
  emmeans( ~ As * Wave) %>%
  contrast(method = "pairwise") %>%
  gather_emmeans_draws() %>%
  ggplot(aes(x = .value, y = contrast)) +
  stat_halfeye()



marg_eff_attack_0ab <- m_us %>%
  epred_draws(newdata = expand.grid(As = c(0, 1),Wave = c("2018", "2019")),
              re_formula =NA)

saveRDS(marg_eff_attack_0ab,  here::here("_posts", "mus", "mods", "marg_eff_attack_0ab.rds"))
#marg_eff_attack_0ab <- readRDS(here::here("_posts", "mus", "mods", "marg_eff_attack_0ab.rds"))


# Obtain contrasts

marg_eff_attack_0ab
plot_all <- ggplot(
  marg_eff_attack_0ab,
  aes(
    x = .epred,
    y = Wave,
    fill = as.factor(As)
  ) ) + 
#  scale_y_discrete(limits=rev) +
    stat_halfeye() +
    scale_fill_okabe_ito() +
    labs(
      x = "Predicted Warmth Response",
      y = "w2018(years 2018-2019); w2019 (years 2019-2020)",
      fill = "Conterfactual Contrasts",
      subtitle = "Bayesian posterior locations of potential outcomes"
    ) +
  #  scale_x_continuous(limits=c(4.0,4.6)) +
    theme_pubclean() +
    theme(legend.position = "bottom"
    )
plot_all
#plot_all


grand_mean_ame_ab <- m3ab %>% 
  emmeans(~ As*Wave,
          epred = TRUE, re_formula = NA) %>% 
  gather_emmeans_draws() 
   
grand_mean_ame_ab
grand_mean_ame_ab
saveRDS(grand_mean_ame_ab,  here::here("_posts", "mus", "mods", "grand_mean_ame_ab.rds"))
grand_mean_ame_ab <- readRDS(here::here("_posts", "mus", "mods", "grand_mean_ame_ab.rds"))
grand_mean_ame_ab%>%
  slice(10000)
# remove erro contrasts / we don't observe 0 in year two 
test <- grand_mean_ame_ab


plot_all__ame_ab <- ggplot(grand_mean_ame_ab,
                                     aes(x = .value)) +
  stat_halfeye(slab_alpha = 0.75, fill = "grey") +
  scale_fill_okabe_ito(order = c(3, 4)) +
  labs(x = "Average marginal effect of attack on warmth to Muslims",
       y = "Density") +
  #facet_wrap(vars(region)) +
  theme_classic() + 
  theme(legend.position = "bottom") + labs(title= "Marginal effect of attack on warmth to Muslims")
plot_all__ame_ab 
library(patchwork)
bayes_plots_a <- plot_all + plot_all__ame + plot_annotation(tag_levels = 'a')
bayes_plots_a

ggsave(
  bayes_plots_a,
  path = here::here(here::here("_posts", "mus", "figs")),
  width = 10,
  height = 5,
  units = "in",
  filename = "bayes_plots_a.jpg",
  device = 'jpeg',
  limitsize = FALSE,
  dpi = 1200
)

```



## Experimental

```{r}
path_m <- bf(
  yrs ~  As + Wave + (1 | c | Id)
  )
path_y <- bf(
  Ys|mi() ~ As + Wave + yrs + (1 | c | Id)
  )

med1 <- brm(
  path_m + path_y + set_rescor(FALSE)
  data = ka2,
  seed = 1234,
  warmup = 1000,
  iter = 2000,
  chains = 4,
  backend = "cmdstanr",
  file = here::here("_posts", "mus", "mods", "med1")
)

summary(med1)
prior_summary(med1)
lazerhawk::brms_SummaryTable(med1, panderize=F)


## Correct model 
bm_c <- brm_multiple(
  Ys|mi() ~ As * Wave + (1 |  Id),
  prior = c(
    prior(student_t(3, 0, .5), class = Intercept),
    prior(student_t(3, 0, 1), class = "b")),
  data = datlist, # correct data
  seed = 1234,
  warmup = 1000,
  iter = 2000,
  chains = 4,
  backend = "cmdstanr",
  file = here::here("_posts", "mus", "mods", "bm_c"))

#summary(bm_c)

lazerhawk::brms_SummaryTable(bm_c, panderize=F)
plot(bm_c)





```


```{r echo=FALSE, cache = FALSE}
post1F <- brms::posterior_samples(f1a)
post_marF <- post1F %>% 
  transmute(
    a = b_mF_xEarly_March_2020,
    b = b_y_mF_w,
    cp = b_y_xEarly_March_2020,
    me = a * b,
    c = cp + me#,
   # pme = me / c
  )
# posterior_summary(post_marF)
```
```{r}
mcmc_intervals(post_marF)
??mcmc_intervals
```

```




